version: 1.0.{build}

clone_folder: c:\ssiglib\

branches:
  # whitelist
  only:
    - development

skip_tags: true

os: Windows Server 2012
platform: x64
configuration: Release

environment:
  OpenCV_DIR: c:\opencv\build\
  OPENCV_BIN: c:\opencv\build\bin\Release\
  SSIGLib_DIR: c:\ssiglib\build\
  SSIGLib_BIN: c:\ssiglib\build\bin\Release\

before_build:
  - echo =====Starting OpenCV====
  - git clone https://github.com/Itseez/opencv.git c:\opencv\
  - cd c:\opencv
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=c:\opencv\build\ -D WITH_TBB=OFF -D WITH_FFMPEG=ON -D WITH_V4L=OFF -D WITH_OPENMP=OFF -D BUILD_opencv_apps=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D BUILD_WITH_DEBUG_INFO=OFF .. -G "Visual Studio 12 Win64"
  - '"c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64'
  - msbuild ALL_BUILD.vcxproj /p:configuration=release /p:platform=x64 /p:UseEnv=true /p:PreferredToolArchitecture=x64 /p:PlatformToolset=v120
  - echo =====Starting SSIGLib=====
  - cd c:\ssiglib
  - mkdir build
  - cd build
  - cmake -D BUILD_TESTS=ON -D ENABLE_COVERAGE=ON .. -G "Visual Studio 12 Win64"

build_script:
  - cd c:\ssiglib\build\
  - msbuild ALL_BUILD.vcxproj /p:configuration=release /p:platform=x64 /p:UseEnv=true /p:PreferredToolArchitecture=x64 /p:PlatformToolset=v120

build:
  verbosity: minimal
  parallel: true            
#  project: c:\ssiglib\build\ALL_BUILD.vcxproj

before_test:
  - echo ==== Tests ====
  - cd c:\ssiglib\build\
  - '"c:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64'
  - set PATH=%PATH%;%OPENCV_BIN%;

# scripts to run after tests
after_test:

# to run your custom scripts instead of automatic tests
test_script:
  - echo === Hakuna Matata ===
#  - msbuild RUN_TESTS.vcxproj /p:configuration=release /p:platform=x64 /p:UseEnv=true /p:PreferredToolArchitecture=x64 /p:PlatformToolset=v120
#  - for /D %%D in (c:\ssiglib\data\tests\*) do ( copy /y %%D\* c:\ssiglib\build\bin\Release\ )
  - ctest -C Release -V --output-on-failure --test-timeout 270 
#  - copy /Y c:\opencv\build\bin\Release\*.dll c:\ssiglib\build\bin\Release\
#  - c:\ssiglib\build\bin\Release\test_core.exe
#  - c:\ssiglib\build\bin\Release\test_ml.exe
#  - c:\ssiglib\build\bin\Release\test_descriptors.exe
#  - c:\ssiglib\build\bin\Release\test_hashing.exe

notifications:
  # Email
  - provider: Email
    to:
      - rbk@dcc.ufmg.br
    subject: 'Build {{status}}'                  
#    message: "{{message}}, {{commitId}}, ..."    
    on_build_status_changed: true
